### ISSUE TITLE
Python3.5 + compatible

### ISSUE THREAD

**Issue by Nadia0731** [piglei/uwsgi-sloth#10]
Python3.5 + compatible. In the file 'uwsgi_sloth/models.py', line 43, fp needs to be encoded or a type error will be reported.For example: fp = fp. encode ()

**Comment by Nadia0731** [comment]
if type error in 43 number,add :    fp = fp. encode ()

**Comment by piglei** [comment]
The latest version 3.0.0+ should be compatible with Python 3.5+, please provide more details on this bug.
