### ISSUE TITLE
No Data in latest_5_mins.html

### ISSUE THREAD

**Issue by Gromph** [piglei/uwsgi-sloth#9]
Hi, I just tried setting up version 2.1.2 from pypi on CentOS 7, with python 2.7.5, uWSGI 2.0.13.1 and everything appeared to work and it generated the latest_5_mins.html page, but it shows 0 requests. 

My uwsgi log file is stock, here is a sample from it:
[pid: 18227|app: 0|req: 203555/404742] 10.10.0.1 () {50 vars in 908 bytes} [Sat Aug 20 20:32:37 2016] GET /api/tournaments/53822/ => generated 1851 bytes in 121 msecs (HTTP/1.1 200) 4 headers in 149 bytes (1 switches on core 0)
[pid: 18563|app: 0|req: 201188/404743] 10.10.0.1 () {48 vars in 1013 bytes} [Sat Aug 20 20:32:37 2016] GET /api/tournaments/54496/ => generated 1835 bytes in 116 msecs (HTTP/1.1 200) 4 headers in 149 bytes (1 switches on core 0)

/var/www/uwsgi_sloth/tk.conf
uwsgi_log_path = '/var/www/logs/uwsgi.log'
data_dir = '/var/www/uwsgi_sloth/tk/'
domain = 'https://example.com/'  ; Not real domain name, I do have this set correctly in my config

Running it with: 
uwsgi-sloth start -c /var/www/uwsgi_sloth/tk.conf

I also noticed that the demo site shows 0 requests and looks the same as mine:
http://uwsgi-sloth.zlovezl.cn/latest_5mins.html

**Comment by Gromph** [comment]
I believe it might be a timezone problem. I just noticed the time in the logs is in my local timezone PST. But the server is set to utc:
[www@ip-10-10-1-71 www]$ tail -1  /var/www/logs/uwsgi.log
[pid: 30643|app: 0|req: 1250/2584] 69.47.162.7 () {48 vars in 1067 bytes} [Thu Aug 25 12:14:38 2016] GET /api/accounts/415/ => generated 2382 bytes in 33 msecs (HTTP/1.1 200) 4 headers in 129 bytes (1 switches on core 0)

[www@ip-10-10-1-71 www]$ date
Thu Aug 25 19:14:40 UTC 2016

So the problem is most likely with uwsgi logging time in PST instead of UTC.

**Comment by Gromph** [comment]
I got it working by setting the timezone before running uwsgi-sloth:
export TZ=America/Los_Angeles
uwsgi-sloth start -c /var/www/uwsgi_sloth/tourneyking.conf

**Comment by piglei** [comment]
@Gromph  Happy to know you solved the problem, thanks for using uwsgi-sloth.
😄
